/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Jugador.AccesoAleatorio;
import Jugador.Jugador;
import Jugador.ListaRecords;
import static Ventanas.PantallaPrincipal.matriz;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import laberinto.ArchivoTexto;
import laberinto.MatrizLogica;
import laberinto.graphics;

/**
 *
 * @author Ale
 */
public class CreacionJugador extends javax.swing.JFrame {

    private JPasswordField campoContrasenia;

    /**
     * Creates new form CreacionJugador
     */
    public CreacionJugador() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.getContentPane().setBackground(Color.CYAN);
        this.setSize(400, 350);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jT_Nickname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setIconImages(null);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nickname:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 40, 74, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 110, 90, 14);

        jT_Nickname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jT_Nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NicknameActionPerformed(evt);
            }
        });
        getContentPane().add(jT_Nickname);
        jT_Nickname.setBounds(100, 80, 190, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 190, 110, 40);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(110, 140, 130, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/images.jpg"))); // NOI18N
        jLabel5.setLabelFor(this);
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 420, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jT_NicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_NicknameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        String nombre = jT_Nickname.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se ingreso el nombre");
            return;
        }
        String contrasena = String.valueOf(jPasswordField1.getPassword());

        if (contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se ingreso la contrasena");
            return;
        }
        jT_Nickname.setText(" ");
        jPasswordField1.setText("");
        try {
            AccesoAleatorio.crearJugador(new File("Jugadores.txt"));
            
            int i = AccesoAleatorio.buscarRegistroNuevo(nombre, contrasena);
            if (i == -1) {
                JOptionPane.showMessageDialog(null, "Jugador Existente ");
                return;
            }else{
                if (i == 2) {
                    AccesoAleatorio.anadirJugador(new Jugador(nombre, contrasena));
                    PantallaInstrucciones jugar = new PantallaInstrucciones();
                    jugar.setVisible(true);
                    jugar.setTitle("Pantalla de Intrucciones");
                    dispose();
                return;
                }
            }
            AccesoAleatorio.cerrar();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRORRR");
        }
  

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreacionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreacionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreacionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreacionJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CreacionJugador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jT_Nickname;
    // End of variables declaration//GEN-END:variables
}
