/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import static Ventanas.PantallaPrincipal.matriz;
import java.awt.Color;
import laberinto.ArchivoTexto;
import laberinto.Cronometro;
import laberinto.MatrizLogica;
import laberinto.graphics;

/**
 *
 * @author Ale
 */
public class PantallaInstrucciones extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInstrucciones
     */
    public PantallaInstrucciones() {
        initComponents();
         this.getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jC_dificultad = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/chet.jpg"))); // NOI18N
        jButton1.setText("Iniciar Juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/atras.jpg"))); // NOI18N
        jButton2.setText("Regresar al menu Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/play.jpg"))); // NOI18N

        jC_dificultad.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jC_dificultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fácil", "Medio", "Dificíl" }));
        jC_dificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_dificultadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jC_dificultad, 0, 171, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jC_dificultad))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PantallaPrincipal ventana =new PantallaPrincipal();
        ventana.setVisible(true);
          setLocationRelativeTo(null);
        //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String nombreArchivo = " ";
        
        if (jC_dificultad.getSelectedIndex()==0) {
            int facil=(int)(Math.random()*2)+1;
            
            
            if (facil ==1) {
                nombreArchivo = "Tablero1F.txt";
                
            }else if (facil==2) {
                nombreArchivo = "Tablero2F.txt";
                
            }
            System.out.println("nombreArchivo"+nombreArchivo+ "facil"+facil);
            ArchivoTexto a = new ArchivoTexto();
            int[][] tablero = a.leer(nombreArchivo);
            System.out.println(tablero + "  -- PantallaInsctrucciones");

            MatrizLogica ma = new MatrizLogica(tablero);
            new Thread(new Cronometro()).start();
            graphics g = graphics.getInstance();
            g.setAltoAncho(tablero.length, tablero[0].length);
            g.go();
            
        }else if (jC_dificultad.getSelectedIndex()==1) {
            int medio= (int)(Math.random()*(4-3))+3;
            
            if (medio ==3) {
                nombreArchivo = "Tablero1M.txt";
                
            }else if (medio==4) {
                nombreArchivo = "Tablero2M.txt";
                
            }
            ArchivoTexto a = new ArchivoTexto();
            int[][] tablero = a.leer(nombreArchivo);
            System.out.println(tablero + "  -- PantallaInsctrucciones");

            MatrizLogica ma = new MatrizLogica(tablero);
            new Thread(new Cronometro()).start();
            graphics g = graphics.getInstance();
            g.setAltoAncho(tablero.length, tablero[0].length);
            g.go();
            
          }else if (jC_dificultad.getSelectedIndex()==2) {
               int dificil= (int)(Math.random()*(6-5))+5;
              
               if (dificil==5) {
                nombreArchivo = "Tablero1D.txt";
                
            }else if (dificil==6) {
                nombreArchivo = "Tablero2D.txt";
                
            }
          ArchivoTexto a = new ArchivoTexto();
            int[][] tablero = a.leer("Tablero1D.txt");
            System.out.println(tablero + "  -- PantallaInsctrucciones");

            MatrizLogica ma = new MatrizLogica(tablero);
            new Thread(new Cronometro()).start();
            graphics g = graphics.getInstance();
            g.setAltoAncho(tablero.length, tablero[0].length);
            g.go();
          }
        
         
        
//        ArchivoTexto a = new ArchivoTexto();
//        int[][] tablero = a.leer("Tablero1F.txt");
//        System.out.println(tablero + "  -- PantallaInsctrucciones");
//
//        MatrizLogica ma = new MatrizLogica(tablero);
//        new Thread (new Cronometro()).start();
//        graphics g = graphics.getInstance();
//        g.setAltoAncho(tablero.length, tablero[0].length);
//        g.go();
        
        
        
        
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jC_dificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_dificultadActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jC_dificultadActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PantallaInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PantallaInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PantallaInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PantallaInstrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaInstrucciones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jC_dificultad;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
